import Head from 'next/head';
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import { storeWrapper } from '@/state/store';
import { getRunningQueriesThunk, pokemonAPI } from '@/services/api-query.service';
import { PokemonState } from '@/state/reducers/pokemonSlice';
import { useAppSelector } from '@/state/redux-hooks';
// import styles from '@/styles/Home.module.scss';
// className={`${styles.main}`}

export const getServerSideProps: GetServerSideProps<{ data: { cards: PokemonState; }; }> =
  storeWrapper.getServerSideProps((store) => async (context) => {
    const { limit, search, page } = context.query;
    console.log('context: ', context.query);
    
    const pageNumber = Number(page) || 1;
    const limitNumber = Number(limit) || 12;
    const limitNumber2 = search ? 1 : limitNumber;
    const currentOffset = limitNumber * (pageNumber - 1);
    const searchString = search?.toString() || '';
    
    if (searchString === '') {
      store.dispatch(
        pokemonAPI.endpoints.getAllPokemonList.initiate({
           limit: limitNumber2,
           offset: currentOffset,
           search: searchString,
         })
       );
    } else {
      store.dispatch(
        pokemonAPI.endpoints.getPokemon.initiate( searchString)
       );
    }
    await Promise.all(store.dispatch(getRunningQueriesThunk()));
    return {
      props: {
        data: {
          cards: store.getState().pokemon
        },
      },
    };
  });
//{data}: InferGetServerSidePropsType<typeof getServerSideProps>
export default function Home() {
  const pokemon = useAppSelector((state) => state.pokemon.takenPokemon);
  console.log('actual pokemon :', pokemon);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>orange</p>
        {pokemon.map((item) => (
          <p key={item.name}>{item.name}</p>
        ))}
      </main>
    </>
  );
}