import Head from 'next/head';
import { GetServerSideProps } from "next";
import { storeWrapper } from '@/state/store';
import { getRunningQueriesThunk, pokemonAPI } from '@/services/api-query.service';
import { PokemonState } from '@/state/reducers/pokemonSlice';
import { useAppSelector } from '@/state/redux-hooks';
import AppMain from '@/components/main/AppMain';
import { searchActions } from '@/state/reducers/searchSlice';
// import styles from '@/styles/Home.module.scss';
// className={`${styles.main}`}

// eslint-disable-next-line react-refresh/only-export-components
export const getServerSideProps: GetServerSideProps<{ data: { cards: PokemonState; }; }> =
  storeWrapper.getServerSideProps((store) => async (context) => {
    const { limit, search, page } = context.query;
    console.log('context: ', context.query);
    
    const pageNumber = Number(page) || 1;
    const limitNumber = Number(limit) || 12;
    const limitNumber2 = search ? 1 : limitNumber;
    const currentOffset = limitNumber * (pageNumber - 1);
    const searchString = search?.toString() || '';
    
      store.dispatch(
        pokemonAPI.endpoints.getAllPokemonList.initiate({
           limit: limitNumber2,
           offset: currentOffset,
         })
       );
       store.dispatch(
        searchActions.setSearch(searchString)
       )

    await Promise.all(store.dispatch(getRunningQueriesThunk()));
    return {
      props: {
        data: {
          cards: store.getState().pokemon
        },
      },
    };
  });
//{data}: InferGetServerSidePropsType<typeof getServerSideProps>
export default function Home() {
  const pokemon = useAppSelector((state) => state.pokemon.takenPokemon);
  const searc = useAppSelector((state) => state.search.search);
  console.log('actual pokemon :', pokemon);
  console.log('actual serach: ', searc);
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppMain></AppMain>
      </main>
    </>
  );
}